void showTrains(char *, char *);
int generatePnr(void);
void updateFare(int, char tr_date[], char class[], int);
int printTicket(void);
int pnrCheck(void);
int revenueCheck(void);
int seatHistory(void);
int seatStatus(void);
void seatACdate(void);
// Return_Station_names startBooking(void);
// int seatAvailability(int, int, StoD);
// Passenger_Details bookTicket(void);
// void update_in_file(int, Seat_Count tt[3][4], Train_Date dt[3]);
int systemStart(void);
void dumpUserCredFile(char *, long long);
void nLogPortal(void);
int uLogPortal(void);
void aLogPortal(void);
int randomPrime(void);
long long hash(char *);
char* passTake(void);
int checkPass(char *, long long);
long long chk_ID_get_key(char *, int);
